164402 - Andrey Vinicius Santos Souza

In [1]:
import numpy as np

def arredondar(num, sig=6):
    """Arredonda um número para um número fixo de algarismos significativos."""
    if num == 0:
        return 0.0
    else:
        return float(f"{num:.{sig}g}")

def arredondar_matriz(mat, sig=6):
    """Aplica arredondamento a todos os elementos de uma matriz."""
    return np.vectorize(lambda x: arredondar(x, sig))(mat)

def substituicao_regressiva(Ab, sig=6):
    """Executa substituição regressiva para resolver o sistema triangular superior."""
    n = len(Ab)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        soma = sum(arredondar(Ab[i, j] * x[j], sig) for j in range(i+1, n))
        x[i] = arredondar((Ab[i, -1] - soma) / Ab[i, i], sig)
        print(f"\n🔻 Substituição regressiva para x{i+1}: {x[i]:.8f}")
    return x

def eliminacao_gauss_pivotamento(A, b, sig=6):
    """Executa a Eliminação de Gauss com pivotamento parcial e imprime cada passo."""
    n = len(A)
    Ab = np.hstack((A, b.reshape(-1, 1)))  # Matriz aumentada

    print("\n🔢 Matriz aumentada inicial:")
    print(arredondar_matriz(Ab, sig))

    # Eliminação com pivotamento parcial
    for i in range(n):
        print(f"\n🔄 Passo {i+1} - Início da iteração")

        # Pivotamento parcial
        max_idx = np.argmax(np.abs(Ab[i:, i])) + i
        if i != max_idx:
            Ab[[i, max_idx]] = Ab[[max_idx, i]]
            print(f"\n🔁 Trocando linha {i+1} com linha {max_idx+1} (pivotamento parcial):")
            print(arredondar_matriz(Ab, sig))
        else:
            print(f"\n🔁 Nenhuma troca de linhas necessária.")

        # Eliminação de Gauss (para zerar abaixo do pivô)
        for j in range(i+1, n):
            if Ab[i, i] == 0:
                print(f"⚠️ Pivô nulo na linha {i+1}, não é possível continuar.")
                continue
            fator = arredondar(Ab[j, i] / Ab[i, i], sig)
            print(f"\n🔨 Calculando fator de eliminação: {fator} para a linha {j+1}")

            for k in range(i, n+1):
                Ab[j, k] = arredondar(Ab[j, k] - fator * Ab[i, k], sig)

            print(f"\n📊 Após eliminação da linha {j+1}:")
            print(arredondar_matriz(Ab, sig))

    print("\n📐 Matriz triangular superior:")
    print(arredondar_matriz(Ab, sig))

    # Substituição regressiva
    x = substituicao_regressiva(Ab, sig)

    print("\n✅ Solução final (com 8 casas decimais):")
    for i, valor in enumerate(x, 1):
        print(f"x{i} = {valor:.8f}")

    return x

def entrada_usuario():
    """Faz a entrada interativa da matriz e vetor."""
    try:
        tamanho = input("Digite o tamanho da matriz no formato 'nxn' (ex: 3x3): ").lower().strip()
        n = int(tamanho.split('x')[0])

        A = np.zeros((n, n))
        b = np.zeros(n)

        print("\n📥 Preenchendo a matriz A (coeficientes do sistema):")
        for i in range(n):
            for j in range(n):
                A[i, j] = float(input(f"  a{i+1}{j+1} = "))

        print("\n📥 Preenchendo o vetor b (termos independentes):")
        for i in range(n):
            b[i] = float(input(f"  b{i+1} = "))

        return A, b

    except Exception as e:
        print(f"\n❌ Erro de entrada: {e}")
        return None, None

# Execução principal
A, b = entrada_usuario()
if A is not None and b is not None:
    eliminacao_gauss_pivotamento(A, b, sig=6)



📥 Preenchendo a matriz A (coeficientes do sistema):

📥 Preenchendo o vetor b (termos independentes):

🔢 Matriz aumentada inicial:
[[  3.   1.  -1. 500.]
 [  2.   4.   1. 800.]
 [  1.  -2.   5. 300.]]

🔄 Passo 1 - Início da iteração

🔁 Nenhuma troca de linhas necessária.

🔨 Calculando fator de eliminação: 0.666667 para a linha 2

📊 Após eliminação da linha 2:
[[ 3.00000e+00  1.00000e+00 -1.00000e+00  5.00000e+02]
 [-1.00000e-06  3.33333e+00  1.66667e+00  4.66666e+02]
 [ 1.00000e+00 -2.00000e+00  5.00000e+00  3.00000e+02]]

🔨 Calculando fator de eliminação: 0.333333 para a linha 3

📊 Após eliminação da linha 3:
[[ 3.00000e+00  1.00000e+00 -1.00000e+00  5.00000e+02]
 [-1.00000e-06  3.33333e+00  1.66667e+00  4.66666e+02]
 [ 1.00000e-06 -2.33333e+00  5.33333e+00  1.33334e+02]]

🔄 Passo 2 - Início da iteração

🔁 Nenhuma troca de linhas necessária.

🔨 Calculando fator de eliminação: -0.7 para a linha 3

📊 Após eliminação da linha 3:
[[ 3.00000e+00  1.00000e+00 -1.00000e+00  5.00000e+02]
 [-1

## Resolução de um Sistema Linear com Eliminação de Gauss e Pivotamento Parcial

Para determinar os valores de $x$, $y$ e $z$, que representam as demandas de transporte entre três cidades, utilizamos o **algoritmo da eliminação de Gauss com pivotamento parcial**, implementado em Python. Esse método é eficiente e sistemático para resolver sistemas lineares, mesmo quando os coeficientes envolvem números grandes ou de precisão sensível.

O sistema de equações dado foi:

$$
\begin{cases}
3x + y - z = 500 \\
2x + 4y + z = 800 \\
x - 2y + 5z = 300
\end{cases}
$$

Através do algoritmo, o sistema foi transformado em uma **matriz triangular superior** por meio de operações elementares e, posteriormente, resolvido com **substituição regressiva**. O **pivotamento parcial** foi aplicado em cada etapa da eliminação para garantir maior estabilidade numérica, evitando divisões por valores muito pequenos.

---

### ✅ Resultado Final:

Após a execução do método, obtivemos os seguintes valores aproximados (com 8 casas decimais):

- **$x$** = $155.38500000$
- **$y$** = $104.61500000$
- **$z$** = $70.76920000$
